# Generated by Django 5.2.7 on 2025-11-14 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('region', models.CharField(help_text='Kod regionu lub kraju, np. PL, DE, CZ', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=100)),
                ('plec', models.CharField(choices=[('K', 'Kobieta'), ('M', 'Mężczyzna'), ('I', 'Inna')], default='I', max_length=1)),
                ('data_dodania', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, help_text='Krótki opis rodzaju nieruchomości.')),
                ('typical_features', models.CharField(blank=True, help_text='Typowe cechy tego typu nieruchomości (np. metraż, liczba pokoi).', max_length=200)),
                ('is_residential', models.BooleanField(default=True, help_text='Czy nieruchomość jest mieszkalna.')),
                ('popularity_rank', models.PositiveSmallIntegerField(default=0, help_text='Ocena standardu (0–10) według użytkowników portalu.')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('listing_month', models.IntegerField(choices=[(1, 'Styczeń'), (2, 'Luty'), (3, 'Marzec'), (4, 'Kwiecień'), (5, 'Maj'), (6, 'Czerwiec'), (7, 'Lipiec'), (8, 'Sierpień'), (9, 'Wrzesień'), (10, 'Październik'), (11, 'Listopad'), (12, 'Grudzień')], default=1)),
                ('transaction_type', models.CharField(choices=[('S', 'Sprzedaż'), ('W', 'Wynajem')], default='S', max_length=1)),
                ('available_units', models.PositiveIntegerField(default=1, help_text='Liczba pokoi')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal_nieruchomosci.agent')),
                ('property_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal_nieruchomosci.propertytype')),
            ],
        ),
    ]
