# Generated by Django 5.2.7 on 2025-11-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_nieruchomosci', '0002_stanowisko_klient_stanowisko'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klient',
            name='stanowisko',
        ),
        migrations.AddField(
            model_name='agent',
            name='stanowisko',
            field=models.CharField(choices=[('A', 'Agent nieruchomości'), ('D', 'Doradca sprzeday'), ('O', 'Osoba prywatna'), ('F', 'Firma')], default='A', max_length=1),
        ),
        migrations.DeleteModel(
            name='Stanowisko',
        ),
    ]
