# Generated by Django 5.2.7 on 2025-12-19 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_nieruchomosci', '0007_property_ac_property_balcony_property_garage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='wlasciciel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='klienci', to=settings.AUTH_USER_MODEL),
        ),
    ]
