# Generated by Django 5.2.7 on 2026-01-16 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_nieruchomosci', '0009_property_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klient',
            name='wlasciciel',
        ),
        migrations.AddField(
            model_name='klient',
            name='agenci',
            field=models.ManyToManyField(blank=True, related_name='klienci', to=settings.AUTH_USER_MODEL),
        ),
    ]
